apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: striim-extdata-claim
  name: striim-extdata-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: striim-extes-claim
  name: striim-extes-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: striim-extlib-claim
  name: striim-extlib-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: striim-mdr-claim
  name: striim-mdr-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: striim-extupload-claim
  name: striim-extupload-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: striim-metadatarepo
  name: striim-metadatarepo
spec:
  selector:
    matchLabels:
      io.kompose.service: striim-metadatarepo
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: striim-metadatarepo
    spec:
      containers:
      # Modify this to an actual Striim Release Version
      - image: docker.io/striim/striim-dbms:latest
        name: striim-metadatarepo
        ports:
        - containerPort: 1527
        resources: {}
        volumeMounts:
        - mountPath: /var/striim/dereby
          name: striim-mdr-storage
      restartPolicy: Always
      volumes:
      - name: striim-mdr-storage
        persistentVolumeClaim:
          claimName: striim-mdr-claim
status: {}
---


apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: striim-node
  name: striim-node
spec:
  selector:
    matchLabels:
      io.kompose.service: striim-node
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: striim-node
    spec:
      containers:
      - name: striim-node
        # Modify this to an actual Striim Release Version
        image: docker.io/striim/striim-node:4.0.4.3
        env:  
        - name: STRIIM_CLUSTER_NAME
          value: "dockerizedstriimcluster"
        # - name: STRIIM_COMPANY_NAME
        #   value: "Striim"
        # Modify this with company recieved from Sales team
        - name: STRIIM_COMPANY_NAME
          # Modify this with company recieved from Sales team
          value: "Striim"
        - name: STRIIM_LICENSE_KEY
          # Modify this with license key received from Sales team
          value: ""
        - name: STRIIM_PRODUCT_KEY
          # Modify this with product key recieved from Sales team
          value: ""
        - name: STRIIM_METADATAREPO_ADDR
          value: striim-metadatarepo:1527
        # FREE TRIAL USE: ACCEPT EULA, Enter a valid first name, last name and company email address
        - name: STRIIM_ACCEPT_EULA
          value: "Y"
        # - name: STRIIM_FIRST_NAME
        #   value: "Sweta"
        # Modify this with your real first name
        - name: STRIIM_FIRST_NAME
          # Modify this with your real first name
          value: "Sweta"
        # - name: STRIIM_LAST_NAME
        #   value: "Garai"
        # Modify this with your real last name
        - name: STRIIM_LAST_NAME
          # Modify this with your real last name
          value: "Garai"
        # - name: STRIIM_COMPANY_EMAIL_ADDRESS
        #   value: "abc.def@striim.com"
        - name: STRIIM_COMPANY_EMAIL_ADDRESS
          # Modify this with your real company email address
          value: "abc.def@striim.com"
        - name: STRIIM_METADATAREPO_DB
          value: "derby"
        - name: STRIIM_MAX_MEMORY
          value: "4096m"
        - name: STRIIM_L4J_ROOT_LOGGER
          value: "warn"
        - name: STRIIM_L4J_MAX_FILE_SIZE
          value: "100MB"
        - name: STRIIM_L4J_MAX_BACKUP_IDX
          value: "4"
        - name: STRIIM_TRACK_FLM
          value: "false"
        - name: STRIIM_EVICTTHRESHOLD
          value: "25"
        

        ports:
        - containerPort: 9080
        resources: {}
        volumeMounts:
        - mountPath: /opt/striim/extlib
          name: striim-extlib-storage
        - mountPath: /opt/striim/data
          name: striim-extdata-storage
        - mountPath: /opt/striim/elasticsearch
          name: striim-extes-storage
        - mountPath: /opt/striim/UploadedFiles
          name: striim-extupload-storage
        # - mountPath: /etc/secret-volume
        #   name: secret-volume
      restartPolicy: Always
      volumes:
      - name: striim-extlib-storage
        persistentVolumeClaim:
          claimName: striim-extlib-claim
      - name: striim-extdata-storage
        persistentVolumeClaim:
          claimName: striim-extdata-claim
      - name: striim-extes-storage
        persistentVolumeClaim:
          claimName: striim-extes-claim
      - name: striim-extupload-storage
        persistentVolumeClaim:
          claimName: striim-extupload-claim          
      # - name: secret-volume
      #   secret:
      #     secretName: striim-secret
status: {}
---


apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: striim-metadatarepo
  name: striim-metadatarepo
spec:
  ports:
  - name: "1527"
    port: 1527
    targetPort: 1527
  selector:
    io.kompose.service: striim-metadatarepo
status:
  loadBalancer: {}
--- 

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: striim-node
  name: striim-node
spec:
  type: LoadBalancer   
  ports:
  - name: "9080"
    port: 9080
    targetPort: 9080
  selector:
    io.kompose.service: striim-node
status:
  loadBalancer: {}

